steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/econoguide-frontend'
      - '--build-arg'
      - 'REACT_APP_API_URL=${_API_URL}'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/econoguide-frontend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'econoguide-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/econoguide-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--timeout'
      - '300s'

images:
  - 'gcr.io/$PROJECT_ID/econoguide-frontend'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _API_URL: 'https://backend-url'